# Workflow for deploying a React app to GitHub Pages
name: Deploy React App to GitHub Pages

on:
  # Run this workflow on pushes to the main branch or when triggered manually
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js (required for building the React app)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies and build the React app
      - name: Install and Build
        run: |
          npm install
          npm run build

      # Upload the build output as an artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build' # Path to the React app build output

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
